config/routes.rb
Dentalassistant::Application.routes.draw do
  get "appointment/index"

  get "dayavailable/index"

  resources :available_times

  resources :locations

  resources :dentistries
  match "appointment" => "appointment#index"
  match "appointment/index" => "appointment#index"
  match "dayavailables" => "dayavailable#index"
  match "login" => "user_sessions#new", :as => :login
  match "logout" => "user_sessions#destroy", :as => :logout
  match "editprofile" => "user#edit", :as => :editprofile
  resources :users
  resources :user_sessions
  resources :medicalhistories
  resources :forms
  root :to => 'medicalhistories#new'

end

app/models/dentistry.rb
class Dentistry < ActiveRecord::Base
  attr_accessible :name, :address, :phone
  has_many :locations
end

app/controllers/dentistries_controller.rb
class DentistriesController < ApplicationController
  def index
    @dentistries = Dentistry.all
  end

  def show
    @dentistry = Dentistry.find(params[:id])
  end

  def new
    @dentistry = Dentistry.new
  end

  def create
    @dentistry = Dentistry.new(params[:dentistry])
    if @dentistry.save
      redirect_to @dentistry, :notice => "Successfully created dentistry."
    else
      render :action => 'new'
    end
  end

  def edit
    @dentistry = Dentistry.find(params[:id])
  end

  def update
    @dentistry = Dentistry.find(params[:id])
    if @dentistry.update_attributes(params[:dentistry])
      redirect_to @dentistry, :notice  => "Successfully updated dentistry."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @dentistry = Dentistry.find(params[:id])
    @dentistry.destroy
    redirect_to dentistries_url, :notice => "Successfully destroyed dentistry."
  end
end

app/helpers/dentistries_helper.rb
module DentistriesHelper
end

app/views/dentistries/_form.html.erb
<%= form_for @dentistry do |f| %>
  <%= f.error_messages %>
<div class="group">
  <div class="wide_box">
    <div class="inner">
  <table border="">
   <tr>
    <td><%= f.label :name %></td>
    <td><%= f.text_field :name %></td>
  </tr>
  <tr>
    <td><%= f.label :address %></td>
    <td><%= f.text_field :address %></td>
  </tr>
  <tr>
    <td><%= f.label :phone %></td>
    <td><%= f.text_field :phone %></td>
  </tr>
  <tr><td><%=positive_button_submit_tag "Add Dentistry"%></td></tr>
  </table>
  </div>
  </div>
  </div>
<% end %>

app/views/dentistries/edit.html.erb
<% title "Edit Dentistry" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @dentistry %> |
  <%= link_to "View All", dentistries_path %>
</p>

app/views/dentistries/index.html.erb
<% title "Dentistries" %>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
  </tr>
  <% for dentistry in @dentistries %>
    <tr>
      <td><%= dentistry.name %></td>
      <td><%= dentistry.address %></td>
      <td><%= dentistry.phone %></td>
      <td><%= link_to "Show", dentistry %></td>
      <td><%= link_to "Edit", edit_dentistry_path(dentistry) %></td>
      <td><%= link_to "Destroy", dentistry, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Dentistry", new_dentistry_path %></p>

app/views/dentistries/new.html.erb
<%= render 'form' %>

app/views/dentistries/show.html.erb
<% title "Dentistry" %>

<p>
  <strong>Name:</strong>
  <%= @dentistry.name %>
</p>
<p>
  <strong>Address:</strong>
  <%= @dentistry.address %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @dentistry.phone %>
</p>

<p>
  <%= link_to "Edit", edit_dentistry_path(@dentistry) %> |
  <%= link_to "Destroy", @dentistry, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", dentistries_path %>
</p>