config/routes.rb
Dentalassistant::Application.routes.draw do
  get "appointment/index"

  get "dayavailable/index"

  resources :available_times

  resources :locations

  resources :dentistries
  match "appointment" => "appointment#index"
  match "appointment/index" => "appointment#index"
  match "dayavailables" => "dayavailable#index"
  match "login" => "user_sessions#new", :as => :login
  match "logout" => "user_sessions#destroy", :as => :logout
  match "editprofile" => "user#edit", :as => :editprofile
  resources :users
  resources :user_sessions
  resources :medicalhistories
  resources :forms
  root :to => 'medicalhistories#new'

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def index
    @forms = Forms.all
  end

  def show
    @forms = Forms.find(params[:id])
  end

  def new
    @forms = Forms.new
  end

  def create
    @forms = Forms.new(params[:forms])
    if @forms.save
      redirect_to @forms, :notice => "Successfully created forms."
    else
      render :action => 'new'
    end
  end

  def edit
    @forms = Forms.find(params[:id])
  end

  def update
    @forms = Forms.find(params[:id])
    if @forms.update_attributes(params[:forms])
      redirect_to @forms, :notice  => "Successfully updated forms."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @forms = Forms.find(params[:id])
    @forms.destroy
    redirect_to forms_url, :notice => "Successfully destroyed forms."
  end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= form_for @forms do |f| %>
  	<%= f.error_messages %>

	<%= f.input :fname, :hint => 'hello'%>
	<%= f.input :lname, :hint => 'test' %>
	<%= f.button :submit %>

<% end %>

app/views/forms/edit.html.erb
<% title "Edit Forms" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @forms %> |
  <%= link_to "View All", forms_path %>
</p>

app/views/forms/index.html.erb
<% title "Forms" %>

<table>
  <tr>
    <th>Fname</th>
    <th>Lname</th>
  </tr>
  <% for forms in @forms %>
    <tr>
      <td><%= forms.fname %></td>
      <td><%= forms.lname %></td>
      <td><%= link_to "Show", forms %></td>
      <td><%= link_to "Edit", edit_forms_path(forms) %></td>
      <td><%= link_to "Destroy", forms, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<!--<p><%= link_to "New Forms", new_forms_path %></p>-->

app/views/forms/new.html.erb
<% title "New Forms" %>


<p><%= link_to "Back to List", forms_path %></p>

app/views/forms/show.html.erb
<% title "Forms" %>

<p>
  <strong>Fname:</strong>
  <%= @forms.fname %>
</p>
<p>
  <strong>Lname:</strong>
  <%= @forms.lname %>
</p>

<p>
  <%= link_to "Edit", edit_forms_path(@forms) %> |
  <%= link_to "Destroy", @forms, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", forms_path %>
</p>