config/routes.rb
Dentalassistant::Application.routes.draw do
  get "appointment/index"

  get "dayavailable/index"

  resources :available_times

  resources :locations

  resources :dentistries
  match "appointment" => "appointment#index"
  match "appointment/index" => "appointment#index"
  match "dayavailables" => "dayavailable#index"
  match "login" => "user_sessions#new", :as => :login
  match "logout" => "user_sessions#destroy", :as => :logout
  match "editprofile" => "user#edit", :as => :editprofile
  resources :users
  resources :user_sessions
  resources :medicalhistories
  resources :forms
  root :to => 'medicalhistories#new'

end

app/models/available_times.rb
class AvailableTimes < ActiveRecord::Base
  attr_accessible :mon, :tue, :wed, :thur, :fri, :sat, :sun
  belongs_to :location
end

app/controllers/available_times_controller.rb
class AvailableTimesController < ApplicationController
  def index
    @available_times = AvailableTimes.all
  end

  def show
    @available_times = AvailableTimes.find(params[:id])
  end

  def new
    @available_times = AvailableTimes.new
  end

  def create
    @available_times = AvailableTimes.new(params[:available_times])
    if @available_times.save
      redirect_to @available_times, :notice => "Successfully created available times."
    else
      render :action => 'new'
    end
  end

  def edit
    @available_times = AvailableTimes.find(params[:id])
  end

  def update
    @available_times = AvailableTimes.find(params[:id])
    if @available_times.update_attributes(params[:available_times])
      redirect_to @available_times, :notice  => "Successfully updated available times."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @available_times = AvailableTimes.find(params[:id])
    @available_times.destroy
    redirect_to available_times_url, :notice => "Successfully destroyed available times."
  end
end

app/helpers/available_times_helper.rb
module AvailableTimesHelper
end

app/views/available_times/_form.html.erb
<%= form_for @available_times do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :mon %><br />
    <%= f.check_box :mon %>
  </p>
  <p>
    <%= f.label :tue %><br />
    <%= f.check_box :tue %>
  </p>
  <p>
    <%= f.label :wed %><br />
    <%= f.check_box :wed %>
  </p>
  <p>
    <%= f.label :thur %><br />
    <%= f.check_box :thur %>
  </p>
  <p>
    <%= f.label :fri %><br />
    <%= f.check_box :fri %>
  </p>
  <p>
    <%= f.label :sat %><br />
    <%= f.check_box :sat %>
  </p>
  <p>
    <%= f.label :sun %><br />
    <%= f.check_box :sun %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/available_times/edit.html.erb
<% title "Edit Available Times" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @available_times %> |
  <%= link_to "View All", available_times_path %>
</p>

app/views/available_times/index.html.erb
<% title "Available Times" %>

<table>
  <tr>
    <th>Mon</th>
    <th>Tue</th>
    <th>Wed</th>
    <th>Thur</th>
    <th>Fri</th>
    <th>Sat</th>
    <th>Sun</th>
  </tr>
  <% for available_times in @available_times %>
    <tr>
      <td><%= available_times.mon %></td>
      <td><%= available_times.tue %></td>
      <td><%= available_times.wed %></td>
      <td><%= available_times.thur %></td>
      <td><%= available_times.fri %></td>
      <td><%= available_times.sat %></td>
      <td><%= available_times.sun %></td>
      <td><%= link_to "Show", available_times %></td>
      <td><%= link_to "Edit", edit_available_times_path(available_times) %></td>
      <td><%= link_to "Destroy", available_times, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Available Times", new_available_time_path %></p>

app/views/available_times/new.html.erb
<% title "New Available Times" %>

<%= render 'form' %>

<p><%= link_to "Back to List", available_times_path %></p>

app/views/available_times/show.html.erb
<% title "Available Times" %>

<p>
  <strong>Mon:</strong>
  <%= @available_times.mon %>
</p>
<p>
  <strong>Tue:</strong>
  <%= @available_times.tue %>
</p>
<p>
  <strong>Wed:</strong>
  <%= @available_times.wed %>
</p>
<p>
  <strong>Thur:</strong>
  <%= @available_times.thur %>
</p>
<p>
  <strong>Fri:</strong>
  <%= @available_times.fri %>
</p>
<p>
  <strong>Sat:</strong>
  <%= @available_times.sat %>
</p>
<p>
  <strong>Sun:</strong>
  <%= @available_times.sun %>
</p>

<p>
  <%= link_to "Edit", edit_available_times_path(@available_times) %> |
  <%= link_to "Destroy", @available_times, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", available_times_path %>
</p>