config/routes.rb
Dentalassistant::Application.routes.draw do
  get "appointment/index"

  get "dayavailable/index"

  resources :available_times

  resources :locations

  resources :dentistries
  match "appointment" => "appointment#index"
  match "appointment/index" => "appointment#index"
  match "dayavailables" => "dayavailable#index"
  match "login" => "user_sessions#new", :as => :login
  match "logout" => "user_sessions#destroy", :as => :logout
  match "editprofile" => "user#edit", :as => :editprofile
  resources :users
  resources :user_sessions
  resources :medicalhistories
  resources :forms
  root :to => 'medicalhistories#new'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DentalAssist App</title>
    <%= css3buttons_stylesheets %>
    <%= stylesheet_link_tag "application", :media => 'all'%>
    <%= stylesheet_link_tag "button-basics", :media => 'all'%>
    <%= stylesheet_link_tag "global" %>
    <%= stylesheet_link_tag "token-input-facebook.css"%>
    <%= stylesheet_link_tag "jquery-ui-timepicker.css"%>
    <%= stylesheet_link_tag "fancybox.css"%>
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/smoothness/jquery-ui.css" type="text/css" media="all" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/jquery-ui.min.js" type="text/javascript"></script>
    <%= javascript_include_tag :defaults%>
    <%= javascript_include_tag 'jquery.maskedinput.js', 'jquery.tokeninput','jquery.ui.timepicker.js' %>
    <script src="/javascripts/jquery.maskedinput.js" type="text/javascript"></script> 
    <script src="/javascripts/fancybox.js"></script>
        <%= csrf_meta_tag %>
      <%= yield(:head) %>

  </head>
  <body>
<!--<div class="wrapped">
                <div class="column" id="product-nav">
                    <h3>The Bundle</h3>
                    <ul>
                            <li rel="258" class="active"><a href="javascript:void(0)">Loop11</a></li>
                            <li rel="269"><a href="javascript:void(0)">page.ly</a></li>
                            <li rel="280"><a href="javascript:void(0)">WebCollaboration</a></li>
                    </ul>
                    <p><a href="/startup-weekend/buy/">Get the bundle today</a><br>
                </div>
</div>-->
<div id="C_header">
		<div id="C_headerBody">
				<div id="C_userNav">
						<ul id="C_userLinks">
								<li class="C_userNavItem">
                <%if normal_user? %>
                  <%= link_to "Edit Form", edit_medicalhistory_path(current_user.id)%> |
                  <%= link_to "Edit Profile", edit_user_path(:current)%> |
                  <a class="J_loginLink J_onClick headerLogin" href="/logout/">Logout</a>
                <%elsif location_admin?%>
                  <%= link_to "Edit Profile", edit_user_path(:current)%> |
                  <a class="J_loginLink J_onClick headerLogin" href="/logout/">Logout</a>
                <%elsif super_admin?%>
                  <%= link_to "Add Dentistry", new_dentistry_path%> |
                  <%= link_to "Edit Profile", edit_user_path(:current)%> |
                  <a class="J_loginLink J_onClick headerLogin" href="/logout/">Logout</a>
                <%else%>
                  <a class="J_loginLink J_onClick headerLogin" href="/login/">Log in</a>
                <%end%>
                </li>
						</ul>
				</div>
				<div id="C_globalNav">
						<div id="C_tabs">
                <% if location_admin? or super_admin? %>
								<a href="/medicalhistories/">
										<span class="C_tabContent">
										  <span class="C_topBig">Patient Forms</span>
										  <span class="C_topSm">All patients in locaiton</span>
										</span>
								</a>
                <% elsif current_user %>
								<a href="/medicalhistories/">
										<span class="C_tabContent">
										  <span class="C_topBig">Patient Dashboard</span>
										  <span class="C_topSm">Change your preferances</span>
										</span>
								</a>
                <% else %> 
								<a href="/medicalhistories/new">
										<span class="C_tabContent">
										  <span class="C_topBig">New Patients</span>
										  <span class="C_topSm">Fill Forms</span>
										</span>
								</a>
                <% end %>
								<a href="/appointment" class="omnCamp omnic_sn1" id="tabs_start">
										<span class="C_startContainer C_tabContent">
										  <span class="C_topBig">Appointments</span>
										  <span class="C_topSm"><%if location_admin?%>view upcoming appointments<%else%>view scheduled appointments<%end%></span>
										</span>
								</a>
								<a href="/locations" class="omnCamp omnrg_perksheader" >
										<span class="C_startContainer C_tabContent">
										  <span class="C_topBig">Locations</span>
										  <span class="C_topSm"><%if location_admin?%>manage locations<%else%>list locations<%end%></span>
										</span>
								</a>
						</div>
				</div>
		</div>
</div>

<div id="C_pageBody">
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
</div>


  </body>
</html>